### ISSUE TITLE
404 on newsletter creation

### ISSUE THREAD

**Issue by tomnieuwland** [tomnieuwland/clubhaus-php#43]
When I try to create a new newsletter, I get to this screen
![image](https://user-images.githubusercontent.com/17734066/31572230-d849e7f2-b055-11e7-857a-401de02e7fe0.png)

And when I submit the query, it 404's me on this URL
http://localhost/src/student/error.php?err=3

Also the newsletter header says event overview (look at the picture)

**Comment by Geniusflip** [comment]
At the moment all upload files redirect to an error page, I'll push a patch
where some useful errrors are sent instead
