### ISSUE TITLE
clubhaus.events.timeon field is broken

### ISSUE THREAD

**Issue by tomnieuwland** [tomnieuwland/clubhaus-php#50]
Field does not contain intended data
![image](https://user-images.githubusercontent.com/17734066/31580601-95b49b26-b109-11e7-8f49-71a35e60c9a9.png)
 Should be a string with something like 7:30pm - 9:30pm

Can you fix the events that are there when you are done :)

**Comment by Geniusflip** [comment]
Fixed - php was casting strings as ints and adding them
